version: "3.9"

services:
    api:
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile

        image: api:local
        ports:
            - 8080:8080
        # Override lamdba image entrypoint
        entrypoint: ["python", "apps/main.py"]
        environment:
            - ENV=local
