name: Deploy service

on:
  workflow_call:
    inputs:
      env:
        type: string
        default: dev
jobs:
  deploy:
    environment: ${{ inputs.env }}
    name: deploy ${{ inputs.env }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: install serverless
      run: npm i -g serverless
    - name: Configure AWS role to assume
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-duration-seconds: 1200
        role-to-assume: arn:aws:iam::xxxx:role/github-actions-role
        aws-region: us-east-1
    - name: severless deploy
      run: serverless deploy --stage ${{ inputs.env }}
